# Site settings
title: Kubernetes Village
description: >
  Welcome to Kubernetes Village, your own community for all things Kubernetes security. We are dedicated to fostering a vibrant community where Kubernetes security enthusiasts and professionals can converge to share knowledge, exchange ideas, and collaborate on innovative security solutions.

baseurl: "/kubernetesvillage" # the subpath of your site, e.g. /blog/
url: "https://www.kubernetesvillage.com" # the base hostname & protocol for your site

author:
  fullname: Anjali S.
  github: https://github.com/kubernetesvillage
  linkedin: https://www.linkedin.com/in/anjali-s/
  email: peachyclouds3curity@gmail.com

# Syntax highlighting
highlightstyle: 'agate'
styles: [agate, monokai, solarized_dark, solarized_light, github, dark, androidstudio]

# Build settings
highlighter: null
markdown: kramdown
